// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DragDropSQLite(arg1:string):Promise<string>;

export function ExecuteSQL(arg1:string):Promise<Array<any>>;

export function ExportToCSV(arg1:string,arg2:Array<any>):Promise<void>;

export function ExportToJSON(arg1:string,arg2:Array<any>):Promise<void>;

export function ExportToXML(arg1:string,arg2:Array<any>):Promise<void>;
