// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DragDropSQLite(arg1) {
  return window['go']['main']['App']['DragDropSQLite'](arg1);
}

export function ExecuteSQL(arg1) {
  return window['go']['main']['App']['ExecuteSQL'](arg1);
}

export function ExportToCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportToCSV'](arg1, arg2);
}

export function ExportToJSON(arg1, arg2) {
  return window['go']['main']['App']['ExportToJSON'](arg1, arg2);
}

export function ExportToXML(arg1, arg2) {
  return window['go']['main']['App']['ExportToXML'](arg1, arg2);
}
